import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({
  children, 
}: LayoutProps) {
  return (
    <html lang="en">
      <body className='bg-slate-600'>{children}</body>
    </html>
  )
}
